import Foundation

/// Supported languages for conversation agents
public enum Language: String, Codable, Sendable {
    case english = "en"
    case japanese = "ja"
    case chinese = "zh"
    case german = "de"
    case hindi = "hi"
    case french = "fr"
    case korean = "ko"
    case portuguese = "pt"
    case italian = "it"
    case spanish = "es"
    case indonesian = "id"
    case dutch = "nl"
    case turkish = "tr"
    case polish = "pl"
    case swedish = "sv"
    case bulgarian = "bg"
    case romanian = "ro"
    case arabic = "ar"
    case czech = "cs"
    case greek = "el"
    case finnish = "fi"
    case malay = "ms"
    case danish = "da"
    case tamil = "ta"
    case tagalog = "tl"
    case ukrainian = "uk"
    case russian = "ru"
    case hungarian = "hu"
    case norwegian = "no"
    case vietnamese = "vi"
    case latvian = "lv"
    case lithuanian = "lt"
    case slovenian = "sl"
    case slovak = "sk"
    case croatian = "hr"
}
